services:

  aiogram:
    build: .
    ports:
      - "127.0.0.1:${EXPOSE_API:-8000}:8000"
    volumes:
      - type: "bind"
        source: "./log/"
        target: "/app/log/"
      - type: "bind"
        source: "./config/"
        target: "/app/config/"
        read_only: true
      - type: "bind"
        source: "./media/"
        target: "/app/media/"
    depends_on:
      - postgres
      - redis
      - migrations
    restart: always
    entrypoint:
      [ "poetry", "run", "python", "-m", "goToVladi" ]

  flask-admin:
    build: .
    ports:
      - "127.0.0.1:${EXPOSE_FLASK:-5000}:5000"
    volumes:
      - type: "bind"
        source: "./config/"
        target: "/app/config/"
        read_only: true
      - type: "bind"
        source: "./media/"
        target: "/app/media/"
      - type: "bind"
        source: "./gunicorn.conf.py"
        target: "/app/gunicorn.conf.py"
        read_only: true
    depends_on:
      - postgres
      - migrations
    restart: always
    entrypoint:
      [ "poetry", "run", "python", "-m", "goToVladi.flaskadmin" ]
  #   [ "poetry", "run", "gunicorn" ] # TODO fix (тут был косяк с кэшированием запросов в БД, надо почитать)

  faststream:
    build: .
    restart: always
    volumes:
      - type: "bind"
        source: "./config/"
        target: "/app/config/"
        read_only: true
      - type: "bind"
        source: "./media/"
        target: "/app/media/"
    entrypoint:
      [ "poetry", "run", "python", "-m", "goToVladi.mq" ]
    depends_on:
      - rabbitmq

  migrations:
    restart: "no"
    build: .
    volumes:
      - type: "bind"
        source: "./alembic.ini"
        target: "/app/alembic.ini"
        read_only: true
      - type: "bind"
        source: "./config/"
        target: "/app/config/"
        read_only: true
    entrypoint: [ "poetry", "run", "python", "-m", "alembic", "upgrade", "heads" ]
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      - ${DOCKER_ENV_FILE:-.env}
    ports:
      - "${EXPOSE_PG:-5432}:5432"
    volumes:
      - type: "volume"
        source: "postgres"
        target: "/app/pgdata/goToVladi/"
    environment:
      PGDATA: /app/pgdata/goToVladi

  redis:
    image: redis
    restart: always
    ports:
      - "${EXPOSE_REDIS:-6379}:6379"
    command:
      - "redis-server"
      - "--loglevel ${REDIS_LOGLEVEL:-warning}"
      - "--databases 2"
      - "--save 900 1"
      - "--save 300 10"
      - "--save 60 10000"
      - "--maxmemory ${REDIS_MAXMEM:-50mb}"
      - "--maxmemory-policy ${REDIS_POLICY:-noeviction}"
      - "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - type: "volume"
        source: "redis"
        target: "/data/"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "${EXPOSE_RABBITMQ}:5672"
      - "${EXPOSE_RABBITMQ_HTTP}:15672"
    env_file:
      - ${DOCKER_ENV_FILE:-.env}
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - rabbitmq:/var/lib/rabbitmq

volumes:
  redis:
  postgres:
  rabbitmq: