"""empty message

Revision ID: 14bfa761557c
Revises: ad46cf48baff
Create Date: 2024-10-02 22:57:30.935766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bfa761557c'
down_revision: Union[str, None] = 'ad46cf48baff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel_medias', 'content_type')
    op.drop_column('restaurant_medias', 'content_type')
    op.drop_column('trip_medias', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_medias', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('restaurant_medias', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('hotel_medias', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
