"""empty message

Revision ID: 411e104d3064
Revises: 56ee6f6776cc
Create Date: 2024-10-03 04:03:44.269882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411e104d3064'
down_revision: Union[str, None] = '56ee6f6776cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_medias', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_medias', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
