"""empty message

Revision ID: a92c45678206
Revises: 44bd0e23fc13
Create Date: 2024-10-01 12:32:50.194789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92c45678206'
down_revision: Union[str, None] = '44bd0e23fc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hotel_medias_hotel_id_fkey', 'hotel_medias', type_='foreignkey')
    op.create_foreign_key(None, 'hotel_medias', 'hotels', ['hotel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel_medias', type_='foreignkey')
    op.create_foreign_key('hotel_medias_hotel_id_fkey', 'hotel_medias', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###
