"""empty message

Revision ID: 6adad920220e
Revises: 411e104d3064
Create Date: 2024-10-03 17:03:31.627434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6adad920220e'
down_revision: Union[str, None] = '411e104d3064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'restaurants', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_column('restaurants', 'region_id')
    # ### end Alembic commands ###
