"""empty message

Revision ID: 4acceefa247b
Revises: de9a8e814354
Create Date: 2024-09-22 19:18:51.947735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_file

# revision identifiers, used by Alembic.
revision: str = '4acceefa247b'
down_revision: Union[str, None] = 'de9a8e814354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_medias',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content', sqlalchemy_file.types.ImageField(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('restaurants', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('restaurants', 'photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('photos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('restaurants', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_table('restaurant_medias')
    # ### end Alembic commands ###
