"""empty message

Revision ID: a33ec73b4ad1
Revises: 6d8b39b26997
Create Date: 2024-09-11 21:48:11.549245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_file


# revision identifiers, used by Alembic.
revision: str = 'a33ec73b4ad1'
down_revision: Union[str, None] = '6d8b39b26997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('photos', sqlalchemy_file.types.ImageField(), nullable=True))
    op.drop_column('restaurants', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('photo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('restaurants', 'photos')
    # ### end Alembic commands ###
