"""empty message

Revision ID: 90016eb4ebc2
Revises: 06dd4f13c773
Create Date: 2024-10-11 21:52:30.477812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90016eb4ebc2'
down_revision: Union[str, None] = '06dd4f13c773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_events',
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('dt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_events')
    # ### end Alembic commands ###
