"""empty message

Revision ID: e0c0a1712af4
Revises: 136f9ae07df7
Create Date: 2024-09-29 12:38:09.072576

"""
from typing import Sequence, Union

import sqlalchemy_file
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c0a1712af4'
down_revision: Union[str, None] = '136f9ae07df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotels',
    sa.Column('site_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_medias',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlalchemy_file.types.FileField(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    sa.Enum('DELIVERY', 'INNER', name='restaurant_type').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('DELIVERY', 'INNER', name='restaurant_type').create(op.get_bind())
    op.drop_table('hotel_medias')
    op.drop_table('hotels')
    # ### end Alembic commands ###
