"""empty message

Revision ID: 56ee6f6776cc
Revises: 188407648ee5
Create Date: 2024-10-03 03:59:15.137914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ee6f6776cc'
down_revision: Union[str, None] = '188407648ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurant_medias', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('restaurant_medias_restaurant_id_fkey', 'restaurant_medias', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_medias', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant_medias', type_='foreignkey')
    op.create_foreign_key('restaurant_medias_restaurant_id_fkey', 'restaurant_medias', 'restaurants', ['restaurant_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('restaurant_medias', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
