"""empty message

Revision ID: 44bd0e23fc13
Revises: af4177aa5169
Create Date: 2024-10-01 11:53:41.493091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bd0e23fc13'
down_revision: Union[str, None] = 'af4177aa5169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel_districts', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotel_districts', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    op.add_column('hotels', sa.Column('district_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hotels', 'hotel_districts', ['district_id'], ['id'])
    op.drop_column('hotels', 'district')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('district', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hotels', type_='foreignkey')
    op.drop_column('hotels', 'district_id')
    op.drop_constraint(None, 'hotel_districts', type_='foreignkey')
    op.drop_column('hotel_districts', 'region_id')
    # ### end Alembic commands ###
