"""empty message

Revision ID: f9736bd49478
Revises: 2ff5611b8617
Create Date: 2025-02-09 20:35:36.859676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9736bd49478'
down_revision: Union[str, None] = '2ff5611b8617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_texts',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_texts')
    # ### end Alembic commands ###
