"""empty message

Revision ID: ba37758f2931
Revises: 6e21e4a7e5ea
Create Date: 2025-02-10 04:10:15.772329

"""
from typing import Sequence, Union

import sqlalchemy_file
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba37758f2931'
down_revision: Union[str, None] = '6e21e4a7e5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('average_check', sa.Integer(), nullable=False),
    sa.Column('site_url', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('cuisine_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('vk', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('instagram', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('whatsapp', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('telegram', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuisine_id'], ['restaurant_cuisines.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_medias',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlalchemy_file.types.FileField(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('restaurants', 'is_delivery')
    op.drop_column('restaurants', 'is_inner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('is_inner', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('is_delivery', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_table('delivery_medias')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
