"""empty message

Revision ID: 6e21e4a7e5ea
Revises: f9736bd49478
Create Date: 2025-02-09 20:44:36.339050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e21e4a7e5ea'
down_revision: Union[str, None] = 'f9736bd49478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_texts', sa.Column('description', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'message_texts', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_texts', type_='unique')
    op.drop_column('message_texts', 'description')
    # ### end Alembic commands ###
