"""empty message

Revision ID: 9fb9308dc472
Revises: 62b2172f1d17
Create Date: 2025-02-10 06:14:48.039339

"""
from typing import Sequence, Union

import sqlalchemy_file
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb9308dc472'
down_revision: Union[str, None] = '62b2172f1d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sea_recreation_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sea_recreations',
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['sea_recreation_categories.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sea_recreation_medias',
    sa.Column('sea_recreation_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlalchemy_file.types.FileField(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sea_recreation_id'], ['sea_recreations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sea_recreation_medias')
    op.drop_table('sea_recreations')
    op.drop_table('sea_recreation_categories')
    # ### end Alembic commands ###
