"""empty message

Revision ID: 0855f836410c
Revises: 7fbd85e0f673
Create Date: 2025-02-18 19:05:33.907210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0855f836410c'
down_revision: Union[str, None] = '7fbd85e0f673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_rents', 'min_experience',
               existing_type=sa.INTEGER(),
               type_=sa.Float(precision=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_rents', 'min_experience',
               existing_type=sa.Float(precision=3),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
