"""empty message

Revision ID: e627b1a736a6
Revises: 87650098f897
Create Date: 2025-07-24 23:52:33.525530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e627b1a736a6'
down_revision: Union[str, None] = '87650098f897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('button_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_config')
    # ### end Alembic commands ###
