app:
  name: goToVladi
  version: 1

bot:
  token: token
  log-chat: 123456789

  superusers:
    - 12345678


  webhook:
    web-url: https://expamle.com # TODO подстановка из base-url
    path: /webhook
    secret: some_secret

  storage:
    type: redis
    redis:
      host: localhost
      port: 1002
      password: redispassword
      db: 1

db:
  type: postgresql
  connector: asyncpg
  host: localhost
  port: 1001
  login: pguser
  password: pgpassword
  name: dbname

redis:
  host: localhost
  port: 1002
  password: redispassword
  db: 1

api:
  root-path: root-api-path
  enable-logging: true

web:
  base-url: https://expamle.com
